on:
  schedule:
    # nightly at 5am
    - cron: '0 5 * * *'

jobs:
  update-oras-py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Oras-Py Docs
        run: |
          git clone https://github.com/oras-project/oras-py /tmp/oras-py
          cp /tmp/oras-py/docs/1_python.md docs/Client_Libraries/1_python.md

      - name: Push Updates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          printf "GitHub Actor: ${GITHUB_ACTOR}\n"
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git branch
          git add docs/Client_Libraries/1_python.md
          git status

          set +e
          git status | grep modified
          if [ $? -eq 0 ]; then
              set -e
              printf "Changes\n"
              today=$(date '+%Y-%m-%d')
              git commit -a -m "Automated deployment to update oras-py docs ${today}" -m "Signed-off-by: github-actions <github-actions@users.noreply.github.com>"  
              git push origin main
          else
              set -e
              printf "No changes\n"
          fi
